version: '3'
services:
    openailib_cpu:
      image: vegalichacz/openailib_cpu
      container_name: openailib_cpu
      build: .
      ports:
        - 8888:8888
        - 6006:6006
      volumes:
        - C:\\Users\\Onetec\\Workspace\\GitLab\\otrader\\brain\\data:/workspace/data
        - C:\\Users\\Onetec\\Workspace\\GitLab\\otrader\\brain\\notebooks:/workspace/notebooks
        - C:\\Users\\Onetec\\Workspace\\GitLab\\otrader\\brain\\logs:/workspace/logs
      stdin_open: true
      tty: true
